name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '9.0.101'

jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: |
        dotnet restore src/LogProto/LogProto.csproj
        dotnet restore src/Middleware/Middleware.csproj
        dotnet restore test/test.csproj

    - name: Build LogProto
      run: dotnet build src/LogProto/LogProto.csproj --configuration Release --no-restore

    - name: Build Middleware
      run: dotnet build src/Middleware/Middleware.csproj --configuration Release --no-restore

    - name: Build Tests
      run: dotnet build test/test.csproj --configuration Release --no-restore

    - name: Test
      run: dotnet test test/test.csproj --no-restore --verbosity normal